name: Build and Test

on:
  pull_request:
    types: [opened, closed]
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build and Test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.0
      - name: Install Dependencies
        run: |
          if [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - name: Run Unit Tests
        run: npm run test
      - name: Build
        run: npm run build
      - name: Upload Assets to GitHub as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: out